version: 0.0
os: linux
files:
  - source: /
  - destination: /home/ec2-user/GenAIAPP/GenAIAPP
permissions:
  -object: /home/ec2-user/GenAIAPP/GenAIAPP
  pattern: "**"
  owner: ubuntu
  group: ubuntu
hooks:
  BeforeInstall:
  - location: scripts/install_dependencies.sh
  timeout: 300
  runas: ubuntu
ApplicationStart:
  -location: scripts/start_streamlit.sh
  timeout: 300
  runas: ubuntu
