name: Deploy to EC2
on:
 push:
   branches:
     - main
jobs:
 deploy:
   runs-on: ubuntu-latest
   steps:
   - name: Checkout code
     uses: actions/checkout@v2
   - name: Set up SSH keys
     uses: webfactory/ssh-agent@v0.5.3
     with:
       ssh-private-key: ${{ secrets.EC2_KEY }}
   - name: SSH into EC2 and deploy
     run: |
       ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
         cd /home/ec2-user/GenAIAPP
         git pull origin main
         pip3 install -r requirements.txt
         # Check if tmux session exists
         tmux has-session -t streamlit_session 2>/dev/null
         if [ $? != 0 ]; then
           # If session doesn't exist, create a new tmux session and run Streamlit
           tmux new-session -d -s streamlit_session 'streamlit run streamlit2.py --server.port 8501 --server.enableCORS false'
         else
           # If tmux session exists, just send the command to reload Streamlit
           tmux send-keys -t streamlit_session C-c
           tmux send-keys -t streamlit_session 'streamlit run streamlit2.py --server.port 8501 --server.enableCORS false' C-m
         fi
       EOF
