name: Deploy to EC2
on:
 push:
   branches:
     - main
jobs:
 deploy:
   runs-on: ubuntu-latest
   steps:
   - name: Checkout code
     uses: actions/checkout@v2
   - name: Set up SSH keys
     uses: webfactory/ssh-agent@v0.5.3
     with:
       ssh-private-key: ${{ secrets.EC2_KEY }}
   - name: SSH into EC2 and deploy
     run: |
       ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
         cd /home/ec2-user/GenAIAPP
         git pull origin main
         pip3 install -r requirements.txt
         tmux kill-session -t streamlit_session 2>/dev/null || true
         tmux new-session -d -s stream_session 'streamlit run streamlit2.py --server.port 8501 --server.enableCORS false'
       EOF
